/* 테이블 생성 */
CREATE TABLE CATEGORY( 
	CATENUM INT PRIMARY KEY,
	CATEL VARCHAR2(50),
	CATEM VARCHAR2(50)
);

CREATE TABLE PRODUCT( 
	PNUM INT PRIMARY KEY,
	CATENUM INT CONSTRAINT PRODUCT_CATEGORY_FK REFERENCES CATEGORY(CATENUM) ON DELETE CASCADE,
	PNAME VARCHAR2(100) NOT NULL,
	FIXPRICE INT DEFAULT 0,
	SELPRICE INT DEFAULT 0,
	RDATE DATE,
	REPERSON VARCHAR2(20),
	REAGE INT,
	BRAND VARCHAR2(50),
	PIMG VARCHAR2(1000) NOT NULL,
	INFOIMG VARCHAR2(1000) NOT NULL,
	PRODUCTCNT INT DEFAULT 50
);


CREATE TABLE MEMBER( 
   MNUM INT PRIMARY KEY,
   MID VARCHAR2(30) NOT NULL, 
   MPW VARCHAR2(30) NOT NULL,  
   MNAME VARCHAR2(30) NOT NULL,
   MEMAIL VARCHAR2(100) CONSTRAINT MEMAIL_UQ UNIQUE,
   MTEL VARCHAR2(100),
   MPOINT INT,
   ZIPCODE VARCHAR2(50),
   USERADDR VARCHAR2(100),
   DETAILADDR VARCHAR2(100),
   MDATE DATE,
   KAKAOLOGIN VARCHAR2(100)
);

CREATE TABLE DIB( 
   	DIBNUM INT PRIMARY KEY,
	PNUM INT CONSTRAINT DIB_PRODUCT_FK REFERENCES PRODUCT(PNUM) ON DELETE CASCADE,
	MNUM INT CONSTRAINT DIB_MEMBER_FK REFERENCES MEMBER(MNUM) ON DELETE CASCADE,
	DCNT INT
);

CREATE TABLE ADDRESS( 
	ANUM INT PRIMARY KEY,
	MNUM INT CONSTRAINT ADDRESS_MEMBER_FK REFERENCES MEMBER(MNUM) ON DELETE CASCADE,
	SHIPNAME VARCHAR2(20),
	DESTINATION VARCHAR2(20),
	ZIPCODE VARCHAR2(50),
	USERADDR VARCHAR2(100),
	DETAILADDR VARCHAR2(100),
	TEL VARCHAR2(20),
	ISDEFAULT VARCHAR2(1) DEFAULT '0' CONSTRAINT ISDEFAULT_BL CHECK(ISDEFAULT IN('0','1'))
);


CREATE TABLE MORDER(
	ONUM INT PRIMARY KEY,
	MNUM INT CONSTRAINT MORDER_MEMBER_FK REFERENCES MEMBER(MNUM) ON DELETE CASCADE,
	OSHIPNAME VARCHAR2(20),
	OZIPCODE VARCHAR2(50),
	OUSERADDR VARCHAR2(100),
	ODETAILADDR VARCHAR2(50),
	OTEL VARCHAR2(20),
	ODATE DATE,
	OSTATUS INT,
	OPOINT INT
);

CREATE TABLE ORDERDETAIL(
	ODNUM INT PRIMARY KEY,			  
	ONUM INT CONSTRAINT ORDERDETAIL_MORDER_FK REFERENCES MORDER(ONUM) ON DELETE CASCADE,
	PNUM INT CONSTRAINT ORDERDETAIL_PRODUCT_FK REFERENCES PRODUCT(PNUM) ON DELETE CASCADE,
	CNT INT
);

/* 시퀀스 생성 */
CREATE SEQUENCE ANUM_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE DIBNUM_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE MNUM_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE PNUM_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE ONUM_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE ODNUM_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE NOORDER;
